apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: traefik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: pangarabbit
  source:
    repoURL: "https://traefik.github.io/charts"
    targetRevision: 29.0.1
    chart: traefik
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
