apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 30.0.0
# renovate: image=traefik
appVersion: v3.1.0
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "fix: 🐛 ingressroute default name"
    - "fix: namespaced RBACs hub api gateway"
    - "fix: can't set gateway name"
    - "fix(Gateway API): provide expected roles when using namespaced RBAC"
    - "fix(Gateway API)!: revamp Gateway implementation"
    - "feat: ✨ display release name and image full path in installation notes"
    - "feat: use single ingressRoute template"
    - "feat: handle log filePath and noColor"
    - "chore(release): 🚀 publish v30.0.0"
    - "chore(deps): update traefik docker tag to v3.1.0"
